server:
  servlet:
    context-path: /api/v1
  port: 8096

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=sistemaFacturacion
    username: sa
    password: hugo2020

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    hibernate:
      ddl-auto: update
      show-sql: true
